export {default as SearchFlight} from './search-flight';
export {default as Home} from './home';
export {default as Auth} from './auth';
export {default as Settings} from './settings';
export {default as FlightMap} from './flight-map';
export {default as History} from './history';
export {default as Schedule} from './schedule';
export {default as LocationMain} from './location-main';
export {default as LocationMap} from './location-map';